Phishing/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    # 用户url入口
    path('', include('users.urls', namespace='users')),
    # 验证码
    path('captcha/', include('captcha.urls')),
    # 联系人
    path('contacts/', include('contacts.urls', namespace='contacts')),
    # 邮件模板
    path('templets/', include('templets.urls', namespace='templets')),
    # 钓鱼页面
    path('pages/', include('pages.urls', namespace='pages')),
    # 发信配置
    path('smtp/', include('smtp.urls', namespace='smtp')),
    # 任务管理
    path('campaign/', include('campaigns.urls', namespace='campaign')),
    # 控制面板
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

apps/campaigns/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/1/15 14:27
# @Author  : twosmi1e
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

########################################################################################################################
## Django 自带模块导入
########################################################################################################################
from django.urls import path


########################################################################################################################
## 系统自带模块导入
########################################################################################################################
from .views import *
########################################################################################################################
## 自建模块导入
########################################################################################################################


########################################################################################################################
## url
########################################################################################################################
app_name = 'campaigns'

urlpatterns = [
    # 任务列表
    path('list/', CampaignListView.as_view(), name='campaign_list'),
    # 添加任务页面
    path('add/', AddCampaign.as_view(), name='campaign_add'),
    # 添加任务
    path('save/', SaveCampaign.as_view(), name='save_add'),
    # 删除任务
    path('del/<int:ca_id>', DeleteCampaign.as_view(), name='del_campaign'),
    # 执行任务
    path('exec/<int:ca_id>', ExecCampaign.as_view(), name='exec_campaign'),
    # 任务详情
    path('detail/<int:ca_id>', CampaignDetail.as_view(), name='campaign_detail')

]

apps/campaigns/models.py
from django.db import models



# Create your models here.
STATUS = (
     ('0','未开始'),
     ('1','执行中'),
     ('2','已完成'),
     ('3','执行错误'),
     )


class Campaign(models.Model):
    name = models.CharField(max_length=20, verbose_name="任务名称")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    launch_date = models.DateTimeField(null=True, verbose_name="开始时间")
    sendby_date = models.DateTimeField(null=True, verbose_name="结束时间")
    complete_date = models.CharField(blank=True, null=True, verbose_name="完成耗时", default="0", max_length=10)
    status = models.CharField(max_length=20, verbose_name="任务状态", choices=STATUS, default="0")

    group = models.ForeignKey('contacts.Group', verbose_name="分组", on_delete=models.DO_NOTHING, null=True, blank=True)
    templet = models.ForeignKey('templets.Templet', verbose_name="邮件模板", on_delete=models.DO_NOTHING, null=True, blank=True)
    page = models.ForeignKey('pages.Page', verbose_name="钓鱼页面", on_delete=models.DO_NOTHING, null=True, blank=True)
    servers = models.ManyToManyField('smtp.EmailServer', verbose_name="邮件服务器")
    header = models.ForeignKey('smtp.EmailHeader', verbose_name="邮件头", on_delete=models.DO_NOTHING, null=True, blank=True)

    # 任务结果数据统计
    success_num = models.IntegerField(blank=True, default=0, verbose_name="发送成功次数")
    failed_num = models.IntegerField(blank=True, default=0, verbose_name="发送失败次数")
    opened_num = models.IntegerField(blank=True, default=0, verbose_name="已读邮件数")

    class Meta:
        verbose_name = "发送任务"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_servers(self):
        return "\n".join([s.name for s in self.servers.all()])

apps/campaigns/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/1/17 16:45
# @Author  : twosmi1e
# @Site    : 
# @File    : forms.py
# @Software: PyCharm

from django import forms

from .models import *


class AddCampaignForm(forms.ModelForm):
    class Meta:
        model = Campaign
        exclude = []

apps/campaigns/views.py
from django.shortcuts import render

# Create your views here.
########################################################################################################################
## Django 自带模块导入
########################################################################################################################
from django.shortcuts import render, HttpResponseRedirect
from django.views import View
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse
from django.http import HttpResponse, Http404
from django.contrib.auth.hashers import make_password
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.views.decorators.csrf import csrf_protect
########################################################################################################################
## 系统自带模块导入
########################################################################################################################
import time
from pure_pagination import PageNotAnInteger, Paginator, EmptyPage
from email.header import Header #处理邮件主题
from email.mime.text import MIMEText # 处理邮件内容



########################################################################################################################
## 自建模块导入
########################################################################################################################
from .models import *
from utils.mixin_utils import *
from .forms import *
# 目标分组
from contacts.models import Group
# 邮件模板
from templets.models import Templet
# 钓鱼页面
from pages.models import Page
# 邮件服务器
from smtp.models import EmailServer
# 邮件头
from smtp.models import EmailHeader
from .task import *
########################################################################################################################
## 任务列表
########################################################################################################################
class CampaignListView(LoginRequiredMixin, View):
    def get(self, request):
        web_title = 'campaign_manage'
        web_func = 'campaign_list'
        campaigns = Campaign.objects.all()

        keywords = request.GET.get('keywords', '')

        if keywords != '':
            campaigns = campaigns.filter(
                Q(id__icontains=keywords) |
                Q(name__icontains=keywords)
            )


        # 判断页码
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        # 对取到的数据进行分页，记得定义每页的数量
        p = Paginator(campaigns, 9, request=request)

        # 分页处理后的 QuerySet
        campaigns = p.page(page)

        context = {
            'web_title': web_title,
            'web_func': web_func,
            'campaigns': campaigns,
        }


        return render(request, 'campaigns/campaign_list.html', context=context)


########################################################################################################################
## 添加任务
########################################################################################################################
class AddCampaign(LoginRequiredMixin, View):
    def get(self, request):
        web_title = "campaign_manage"
        web_func = "campaign_add"

        groups = Group.objects.all()
        templets = Templet.objects.all()
        pages = Page.objects.all()
        servers = EmailServer.objects.all()
        headers = EmailHeader.objects.all()

        context = {
            'web_title': web_title,
            'web_func': web_func,
            'groups': groups,
            'templets': templets,
            'pages': pages,
            'servers': servers,
            'headers': headers,
        }
        return render(request, 'campaigns/campaign_add.html', context=context)

########################################################################################################################
## 保存任务
########################################################################################################################
class SaveCampaign(LoginRequiredMixin, View):
    def post(self, request):
        add_campaign = AddCampaignForm(request.POST)
        if add_campaign != '':
            campaign = Campaign.objects.create(name=request.POST.get('name'))


            campaign.group = Group.objects.get(id=int(request.POST.get('group')))
            campaign.templet = Templet.objects.get(id=int(request.POST.get('templet')))
            campaign.page = Page.objects.get(id=int(request.POST.get('page')))

            server_list = request.POST.getlist('servers')
            #print(server_list)
            for i in server_list:
                print(i)
                campaign.servers.add(i)

            campaign.header = EmailHeader.objects.get(id=int(request.POST.get('header')))
            campaign.save()
            return HttpResponse('{"status":"success", "msg":"任务添加成功！"}', content_type='application/json')
        return HttpResponse('{"status":"fail", "msg":"任务内容不符合要求！"}', content_type='application/json')

########################################################################################################################
## 执行任务
########################################################################################################################
class ExecCampaign(LoginRequiredMixin, View):
    def post(self, request, ca_id):
        campaign = Campaign.objects.get(id=int(ca_id))

        try:
            task = post_email.delay(ca_id)
            # 改变任务状态
            campaign.status = 1
            campaign.save()
            return HttpResponse('{"status":"success", "msg":"开始执行"}', content_type='application/json')
        except:
            return HttpResponse('{"status":"failed", "msg":"执行失败"}', content_type='application/json')


########################################################################################################################
## 删除任务
########################################################################################################################
class DeleteCampaign(LoginRequiredMixin, View):
    def post(self, request, ca_id):
        try:
            campaign = Campaign.objects.get(id=int(ca_id))
            campaign.delete()
            return HttpResponse('{"status":"success", "msg":"删除成功"}', content_type='application/json')
        except Exception as e:
            return HttpResponse('{"status":"fail", "msg":"删除失败"}', content_type='application/json')


########################################################################################################################
## 任务详情
########################################################################################################################
class CampaignDetail(LoginRequiredMixin, View):
    def get(self, request, ca_id):
        web_title = "campaign_manage"
        web_func = "campaign_detail"
        campaign = Campaign.objects.get(id=int(ca_id))

        task = caculate_time.delay(ca_id)
        context = {
            'web_title': web_title,
            'web_func': web_func,
            'campaign': campaign,
        }

        return render(request, "campaigns/campaign_detail.html", context=context)

templates/campaigns/campaign_add.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
  任务列表
{% endblock title %}


{% block css %}
    <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/select2/dist/css/select2.min.css' %}">
    <link href="{% static 'toastr/toastr.css' %}" rel="stylesheet"/>
    <!-- daterange picker -->
    <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/bootstrap-daterangepicker/daterangepicker.css' %}">
    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="{% static 'adminlet-2.4.10/plugins/iCheck/all.css' %}">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css' %}">
    <!-- Bootstrap time Picker -->
    <link rel="stylesheet" href="{% static 'adminlet-2.4.10/plugins/timepicker/bootstrap-timepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlet-2.4.10/dist/css/AdminLTE.min.css' %}">
    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
{% endblock css %}

<!-- 主体 -->
{% block content %}
<div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">创建任务</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="col-md-8 col-md-offset-2">
                <form method="post" id="addCampaignForm">
                  <div class="form-group">
                      <label>任务名称</label>
                      <input type="text" class="form-control" placeholder="任务名" name="name">
                  </div>

{#                  <div class="form-group">#}
{#                      <label>开始时间</label>#}
{#                      <input type="text" class="form-control" name="launch_date" id="launch_date">#}
{#                  </div>#}
{##}
{#                  <div class="form-group">#}
{#                      <label>结束时间</label>#}
{#                      <input type="text" class="form-control" name="sendby_date" id="sendby_date">#}
{#                  </div>#}

                  <div class="form-group">
                    <label>选择分组</label>
                    <select class="form-control select2" style="width: 100%;" name="group">
                      {% for group in groups %}
                          <option value="{{ group.id }}">{{ group.name }}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <!-- /.form-group -->
                  <div class="form-group">
                    <label>选择邮件模板</label>
                    <select class="form-control select2" style="width: 100%;" name="templet">
                      {% for templet in templets %}
                          <option value="{{ templet.id }}">{{ templet.name }}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>选择钓鱼页面</label>
                    <select class="form-control select2" style="width: 100%;" name="page">
                      {% for page in pages %}
                          <option value="{{ page.id }}">{{ page.name }}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>选择服务器</label>
                    <select class="form-control select2" multiple="multiple" data-placeholder="Select Servers"
                            style="width: 100%;" name="servers">
                        {% for server in servers %}
                            <option value="{{ server.id }}">{{ server.name }}</option>
                        {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>选择邮件头</label>
                    <select class="form-control select2" style="width: 100%;" name="header">
                      {% for header in headers %}
                          <option value="{{ header.id }}">{{ header.name }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </form>
                <div class="fc-button-group col-md-6 col-md-offset-3 ">
                    <button class="btn btn-info" id="saveCampaign">保存</button>
                    <button class="btn btn-default">清空</button>
                </div>

            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">

        </div>
      </div>
      <!-- /.box -->
</div>


{% endblock content %}
{% block script %}
<script>
//保存
$(function () {
    //提交表单
    $('#saveCampaign').on('click', function () {
        toastr.options = {
                closeButton: false,
                debug: false,
                progressBar: false,
                positionClass: "toast-top-right",
                onclick: null,
                showDuration: "300",
                hideDuration: "1000",
                timeOut: "5000",
                extendedTimeOut: "1000",
                showEasing: "swing",
                hideEasing: "linear",
                showMethod: "fadeIn",
                hideMethod: "fadeOut"
              };
        $.ajax({
            cache: false,
            type: "POST",
            url: "{% url 'campaign:save_add' %}",
            dataType: 'json',
            data: $('#addCampaignForm').serialize(),
            async: true,
            beforeSend: function (xhr, settings) {
                // 这里需要csrf_token的值，而不是代码
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function (data) {
                if (data.status == 'success') {
                    toastr.options.timeOut = 1000;
                    toastr.options.onHidden = function() { window.location.href = "{% url 'campaign:campaign_list' %}"; }
                    toastr.success(data.msg);
                } else if (data.status == 'fail') {
                    toastr.options.timeOut = 1000;
                    toastr.error(data.msg);
                }
            }
        })
    })
})
</script>

<!-- bootstrap datepicker -->
<script src="{% static 'adminlet-2.4.10/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'toastr/toastr.min.js' %}"></script>
<script>
  $(function () {
      //Initialize Select2 Elements
      $('.select2').select2()
  });


</script>
{% endblock script %}

templates/campaigns/campaign_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
  任务列表
{% endblock title %}

<!-- 主体 -->
{% block content %}
  <div class="col">
    <p style="height: 2px;"></p>
    <!-- 中间栏 -->
    <div class="padder">
      <!-- 任务列表 -->
      <div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <div style="border-left: 4px solid #003366; margin-bottom: 10px; margin-top: 10px; height: 25px;font-size: 18px;">
              <span>&nbsp;&nbsp;任务列表</span>
            </div>
          </div>
          <div class="panel-body container" style="height: 745px;">
            <div class="module-option clearfix">
              <form class="navbar-form pull-left " role="search" method="get" style="margin-top: 0px;">
                <div class="form-group">
                  <div class="input-group">
                    <input type="text" class="form-control input-sm bg-light no-border rounded" name="keywords"
                           placeholder="关键词搜索" style="width: 150px;">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-sm bg-auto rounded"><i class="fa fa-search"></i></button>
                      </span>
                  </div>
                </div>
              </form>
            </div>


         <div class="row" style="height: 610px;">
                <div class="col-sm-12">

                  <table class="table table-hover table-bordered dataTable" id="departtable" role="grid">

                    <!-- 标题行 -->
                    <thead>
                    <tr role="row">
                      <th class="text-center" rowspan="1" colspan="1" style="">ID</th>
                      <th class="text-center sorting" rowspan="1" colspan="1" style="">任务名称</th>
                      <th class="text-center sorting" rowspan="1" colspan="1" style="">任务状态</th>
                      <th class="text-center" rowspan="1" colspan="1">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for campaign in campaigns.object_list %}
                      <tr class="gradeX {% if forloop.counter|divisibleby:'2' %}odd{% else %}even{% endif %}"
                          role="row">
                        <td class="text-center" style="vertical-align : middle;">{{ forloop.counter }}</td>
                        <td class="text-center" style="vertical-align : middle;">{{ campaign.name }}</td>
                      {% if campaign.status == "2"%}
                        <td class="text-center" style="vertical-align: middle;"><span class="badge bg-green">{{ campaign.get_status_display }}</span></td>
                      {% else %}
                        <td class="text-center" style="vertical-align: middle;"><span class="badge bg-red">{{ campaign.get_status_display }}</span></td>
                      {% endif %}
                        <td class="text-center" style="vertical-align: middle;">
                            <a href="{% url 'campaigns:campaign_detail' campaign.id %}" class="btn btn-info">详情</a>
                            <button class="btn btn-danger" data-toggle="modal" data-target="#DeleteCampaignModal{{ campaign.id }}">删除</button>
                            <button class="btn bg-purple" data-toggle="modal" data-target="#ExecCampaignModal{{ campaign.id }}">执行</button>
                        </td>
                      </tr>
                    {% endfor %}

                    </tbody>
                  </table>



                </div>
              </div>
            </div>

            <!-- 页码 -->
            <div class="row">
              <div class="col-md-12 text-center">
                <ul class="pagination">
                  <!-- 上一页 -->
                  {% if campaigns.has_previous %}
                    <li class="long"><a href="?{{ campaigns.previous_page_number.querystring }}">上一页</a></li>
                  {% endif %}
                  <!-- 页码 -->
                  {% for page in campaigns.pages %}
                    {% if page %}
                      {% ifequal page campaigns.number %}
                        <li class="active"><a href="?page={{ page }}">{{ page }}<span
                                class="sr-only">(current)</span></a></li>
                      {% else %}
                        <li><a href="?{{ page.querystring }}">{{ page }}<span class="sr-only"></span></a></li>
                      {% endifequal %}
                    {% else %}
                      <li><a href="">...<span class="sr-only"></span></a></li>
                    {% endif %}
                  {% endfor %}
                  <!-- 下一页 -->
                  {% if campaigns.has_next %}
                    <li><a href="?{{ campaigns.next_page_number.querystring }}">下一页<span class="sr-only"></span></a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>


          </div>
        </div>
      </div>

    </div>


{% endblock content %}
{% block script %}

<!-- 删除框 -->
{% for campaign in campaigns.object_list %}
    <div class="modal fade modal-warning" id="DeleteCampaignModal{{ campaign.id }}">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">删除任务</h4>
          </div>
          <div class="modal-body">
             <div class="row" id="modal.flashes"></div>
              <form method="post" id="js_deleteCampaignForm{{ campaign.id }}">
                  <div class="form-group">
                      <p>是否删除该任务？</p>
                  </div>
              </form>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">关闭</button>
            <button type="button" class="btn btn-outline" id="js_deleteCampaign{{ campaign.id }}">确认</button>
          </div>
        </div>
      </div>
    </div>

<script>
//删除
    $(function () {
        $('#js_deleteCampaign{{ campaign.id }}').on('click', function () {
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'campaigns:del_campaign' campaign.id %}",
                data: $('#js_deleteCampaignForm{{ depart.id }}').serialize(),
                async: true,
                beforeSend: function (xhr, settings) {
                    // 这里需要csrf_token的值，而不是代码
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    if (data.status == 'success') {
                        toastr.options.timeOut = 1000;
                        toastr.options.onHidden = function() { window.location.href = "{% url 'campaigns:campaign_list' %}"; }
                        toastr.success(data.msg);
                    } else if (data.status == 'fail') {
                        toastr.error(data.msg);
                    }
                }
            });
        });
    })

</script>
{% endfor %}

<!-- 执行框 -->
    {% for campaign in campaigns.object_list %}
        <div class="modal fade" id="ExecCampaignModal{{ campaign.id }}">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">执行</h4>
              </div>
                <div class="modal-body">
             <div class="row" id="modal.flashes"></div>
              <form method="post" id="js_execCampaignForm{{ campaign.id }}">
                  <div class="form-group">
                      <p>执行该任务？</p>
                  </div>
              </form>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">关闭</button>
            <button type="button" class="btn btn-primary" id="js_execCampaign{{ campaign.id }}">执行</button>
          </div>
        </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
        <script>
        //执行任务
        $(function () {
            $('#js_execCampaign{{ campaign.id }}').on('click', function () {
                toastr.options = {
                    closeButton: false,
                    debug: false,
                    progressBar: false,
                    positionClass: "toast-top-right",
                    onclick: null,
                    showDuration: "300",
                    hideDuration: "1000",
                    timeOut: "1000",
                    extendedTimeOut: "1000",
                    showEasing: "swing",
                    hideEasing: "linear",
                    showMethod: "fadeIn",
                    hideMethod: "fadeOut"
                };
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'campaigns:exec_campaign' campaign.id %}",
                    data: $('#js_execCampaign{{ campaign.id }}').serialize(),
                    async: true,
                    beforeSend: function (xhr, settings) {
                      // 这里需要csrf_token的值，而不是代码
                      xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    success: function (data) {
                      if (data.status == 'success') {
                          toastr.options.timeOut = 1000;
                          toastr.options.onHidden = function() { window.location.href = "{% url 'campaigns:campaign_list' %}"; }
                          toastr.success(data.msg);
                      } else if (data.status == 'fail') {
                          toastr.error(data.msg);
                      }
                    }
                });
            })
        })

        </script>
    {% endfor %}

<link href="{% static 'toastr/toastr.css' %}" rel="stylesheet"/>
<script src="{% static 'toastr/toastr.min.js' %}"></script>
{% endblock script %}