Phishing/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    # 用户url入口
    path('', include('users.urls', namespace='users')),
    # 验证码
    path('captcha/', include('captcha.urls')),
    # 联系人
    path('contacts/', include('contacts.urls', namespace='contacts')),
    # 邮件模板
    path('templets/', include('templets.urls', namespace='templets')),
    # 钓鱼页面
    path('pages/', include('pages.urls', namespace='pages')),
    # 发信配置
    path('smtp/', include('smtp.urls', namespace='smtp')),
    # 任务管理
    path('campaign/', include('campaigns.urls', namespace='campaign')),
    # 控制面板
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

apps/templets/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/12/17 19:54
# @Author  : twosmi1e
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

########################################################################################################################
## Django 自带模块导入
########################################################################################################################
from django.urls import path


########################################################################################################################
## 系统自带模块导入
########################################################################################################################
from .views import *
########################################################################################################################
## 自建模块导入
########################################################################################################################


########################################################################################################################
## url
########################################################################################################################
app_name = 'templets'

urlpatterns = [
    # 列表视图
    path('list', IndexView.as_view(), name='templet_list'),
    # 添加模板
    path('add', AddTemplet.as_view(), name='add_templet'),
    # 删除模板
    path('del/<int:t_id>', DeleteTemplet.as_view(), name='del_templet'),
    # 编辑模板
    path('edit/<int:t_id>', EditTemplet.as_view(), name='edit_templet'),
    # 模板详情
    path('detail/<int:t_id>', TempletDetail.as_view(), name='templet_detail'),
]

apps/templets/models.py
from django.db import models


# Create your models here.


class Templet(models.Model):
    name = models.CharField(max_length=20, verbose_name="模板名称")
    subject = models.CharField(max_length=40, verbose_name="邮件标题")
    text = models.TextField(verbose_name="邮件内容")
    attachments = models.FileField(upload_to="attach/%Y/%M", blank=True, verbose_name="附件")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")

    class Meta:
        verbose_name = "邮件模板"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/templets/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/12/17 19:44
# @Author  : twosmi1e
# @Site    : 
# @File    : forms.py
# @Software: PyCharm

from django import forms
from .models import *


class AddTempletForm(forms.ModelForm):
    class Meta:
        model = Templet
        exclude = ['add_time']

apps/templets/views.py
from django.shortcuts import render

# Create your views here.
########################################################################################################################
## Django 自带模块导入
########################################################################################################################
from django.shortcuts import render, HttpResponseRedirect
from django.views import View
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse
from django.http import HttpResponse, Http404
from django.contrib.auth.hashers import make_password
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.views.decorators.csrf import csrf_protect
########################################################################################################################
## 系统自带模块导入
########################################################################################################################
import time
from pure_pagination import PageNotAnInteger, Paginator, EmptyPage


########################################################################################################################
## 自建模块导入
########################################################################################################################
from .forms import *
from .models import *
from utils.mixin_utils import *
from utils.sendmail_utils import *



########################################################################################################################
## 首页类视图
########################################################################################################################
class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        web_title = 'templet_manage'
        web_func = 'templet_list'
        templet = Templet.objects.all()
        keywords = request.GET.get('keywords', '')

        if keywords != '':
            templet = templet.filter(
                Q(id__icontains=keywords) |
                Q(name__icontains=keywords) |
                Q(subject__icontains=keywords)
            )


        # 判断页码
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        # 对取到的数据进行分页，记得定义每页的数量
        p = Paginator(templet, 9, request=request)

        # 分页处理后的 QuerySet
        templet = p.page(page)

        context = {
            'web_title': web_title,
            'web_func': web_func,
            'templets': templet,
        }
        return render(request, 'templets/templet_list.html', context=context)

########################################################################################################################
## 添加模板
########################################################################################################################
class AddTemplet(LoginRequiredMixin, View):
    def post(self, request):
        add_templet = AddTempletForm(request.POST)
        if add_templet.is_valid():
            templet = Templet()
            templet.name = request.POST.get('name')
            templet.subject = request.POST.get('subject')
            templet.text = request.POST.get('text')
            templet.save()
            return HttpResponse('{"status":"success", "msg":"添加模板成功！"}', content_type='application/json')
        else:
            return HttpResponse('{"status":"fail", "msg":"添加模板失败！"}', content_type='application/json')


########################################################################################################################
## CKEDITOR 上传图片
########################################################################################################################
@csrf_protect
def upload_image(request):
    if request.method == 'POST':
        callback = request.GET.get('CKEditorFuncNum')
        try:
            # path 修改上传的路径
            path = "upload/ckeditor/image/" + time.strftime("%Y%m%d%H%M%S",time.localtime())
            f = request.FILES["upload"]
            file_name = path + "_" + f.name
            des_origin_f = open(file_name, "wb+")
            # 直接遍历类文件类型就可以生成迭代器了
            for chunk in f:
                des_origin_f.write(chunk)
            des_origin_f.close()
        except Exception as e:
            print(e)
        res = r"<script>window.parent.CKEDITOR.tools.callFunction("+callback+",'/"+file_name+"', '');</script>"
        return HttpResponse(res)
    else:
        raise Http404()

########################################################################################################################
## 删除模板
########################################################################################################################
class DeleteTemplet(LoginRequiredMixin, View):
    def post(self, request, t_id):
        try:
            templet = Templet.objects.get(id=int(t_id))
            templet.delete()
            return HttpResponse('{"status":"success", "msg":"删除成功"}', content_type='application/json')
        except Exception as e:
            return HttpResponse('{"status":"fail", "msg":"删除失败"}', content_type='application/json')


########################################################################################################################
## 编辑模板
########################################################################################################################
class EditTemplet(LoginRequiredMixin, View):
    def post(self, request, t_id):
        templet = Templet.objects.get(id=int(t_id))
        edit_templet_form = AddTempletForm(request.POST)
        if edit_templet_form:
            templet.subject = request.POST.get('subject')
            templet.text = request.POST.get('text')
            templet.save()
            return HttpResponse('{"status":"success", "msg":"修改模板成功！"}', content_type='application/json')
        else:
            return HttpResponse('{"status":"fail", "msg":"修改模板失败！"}', content_type='application/json')

########################################################################################################################
## 模板详情
########################################################################################################################
class TempletDetail(LoginRequiredMixin, View):
    def get(self, request, t_id):
        web_title = 'templet_manage'
        web_func = 'templet_detail'
        templet = Templet.objects.get(id=int(t_id))
        context = {
            'web_title': web_title,
            'web_func': web_func,
            'templet': templet,
        }
        return render(request, 'templets/templet_detail.html', context=context)

templates/templets/templet_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
  邮件模板
{% endblock title %}

{% block css %}
    <script src="{% static 'ckeditor/ckeditor.js' %}"></script>

{% endblock css %}

<!-- 主体 -->
{% block content %}
<!-- Content Wrapper. Contains page content -->
  <div class="col" style="width: auto">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        邮件模板
      </h1>

    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header">
              <h3 class="box-title">{{ templet.name }}
              </h3>
              <!-- tools box -->

              <div class="pull-right box-tools">
                <button type="button" class="btn btn-info btn-sm" id="js_SaveEdit">保存编辑</button>
                <button type="button" class="btn btn-info btn-sm" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip"
                        title="Remove">
                  <i class="fa fa-times"></i></button>
              </div>
              <!-- /. tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body pad">
              <form id="jd_editTempletForm">
                    <input type="text" class="form-control" name="subject" placeholder="邮件标题" value="{{ templet.subject }}" />
                    <textarea name="text" class="ckeditor" name="text">
                        {{ templet.text|safe }}
                    </textarea>
                  <script>
                      CKEDITOR.replace('text', {
                          height: 550,
                      });
                  </script>
              </form>
            </div>
          </div>

      </div>
      <!-- ./row -->
      </div>
    </section>
  </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}

{% block script %}
<script>
$(function () {
        //处理ckeditor的值
        function CKupdate() {
            for (instance in CKEDITOR.instances)
                CKEDITOR.instances[instance].updateElement();
        }

        //提交表单
        $('#js_SaveEdit').on('click', function () {
            CKupdate();
            //var text = $("#text").val();
            toastr.options = {
                closeButton: false,
                debug: false,
                progressBar: false,
                positionClass: "toast-top-right",
                onclick: null,
                showDuration: "300",
                hideDuration: "1000",
                timeOut: "5000",
                extendedTimeOut: "1000",
                showEasing: "swing",
                hideEasing: "linear",
                showMethod: "fadeIn",
                hideMethod: "fadeOut"
            };
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'templets:edit_templet' templet.id %}",
                dataType: 'json',
                data: $('#jd_editTempletForm').serialize(),
                async: true,
                beforeSend: function (xhr, settings) {
                    // 这里需要csrf_token的值，而不是代码
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    if (data.status == 'success') {
                        toastr.options.timeOut = 1000;
                        toastr.options.onHidden = function() { window.location.href = "{% url 'templets:templet_list' %}"; }
                        toastr.success(data.msg);
                    } else if (data.status == 'fail') {
                        toastr.options.timeOut = 1000;
                        toastr.error(data.msg);
                    }
                }
            });
        })
    });

</script>

<link href="{% static 'toastr/toastr.css' %}" rel="stylesheet"/>
<script src="{% static 'toastr/toastr.min.js' %}"></script>
{% endblock script %}

templates/templets/templet_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
  邮件模板
{% endblock title %}

{% block css %}

<script src="{% static 'ckeditor/ckeditor.js' %}"></script>
{% endblock css %}

<!-- 主体 -->
{% block content %}
  <div class="col">
    <p style="height: 2px;"></p>
    <!-- 中间栏 -->
    <div class="padder">
      <!-- 邮件模板 -->
      <div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <div style="border-left: 4px solid #003366; margin-bottom: 10px; margin-top: 10px; height: 25px;font-size: 18px;">
              <span>&nbsp;&nbsp;邮件模板</span>
            </div>
          </div>
          <div class="panel-body container" style="height: 745px;">
            <div class="module-option clearfix">
              <form class="navbar-form pull-left " role="search" method="get" style="margin-top: 0px;">
                <div class="form-group">
                  <div class="input-group">
                    <input type="text" class="form-control input-sm bg-light no-border rounded" name="keywords"
                           placeholder="关键词搜索" style="width: 150px;">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-sm bg-auto rounded"><i class="fa fa-search"></i></button>
                      </span>
                  </div>
                </div>
              </form>
                <div class="navbar-btn pull-right" style="margin-top: 0px;width: 150px;">
                    <span>
                          <button type="button" class="btn btn-block btn-success" data-toggle="modal" data-target="#AddTempletModal"><i class="fa fa-plus"></i> 添加模板</button>
                      </span>
                </div>
            </div>


         <div class="row" style="height: 610px;">
                <div class="col-sm-12">

                  <table class="table table-hover table-bordered dataTable" id="grouptable" role="grid">

                    <!-- 标题行 -->
                    <thead>
                    <tr role="row">
                      <th class="text-center" rowspan="1" colspan="1" style="">ID</th>
                      <th class="text-center sorting" rowspan="1" colspan="1" style="">模板名</th>
                      <th class="text-center" rowspan="1" colspan="1">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for templet in templets.object_list %}
                      <tr class="gradeX {% if forloop.counter|divisibleby:'2' %}odd{% else %}even{% endif %}"
                          role="row">
                        <td class="text-center" style="vertical-align : middle;">{{ forloop.counter }}</td>
                        <td class="text-center" style="vertical-align : middle;">{{ templet.name }}</td>
                        <td class="text-center" style="vertical-align: middle;">
                            <a href="{% url 'templets:templet_detail' templet.id %}" class="btn btn-info">详情</a>
                            <button class="btn btn-danger" data-toggle="modal" data-target="#DeleteTempletModal{{ templet.id }}">删除</button>
                        </td>
                      </tr>
                    {% endfor %}

                    </tbody>
                  </table>



                </div>
              </div>
            </div>

            <!-- 页码 -->
            <div class="row">
              <div class="col-md-12 text-center">
                <ul class="pagination">
                  <!-- 上一页 -->
                  {% if templets.has_previous %}
                    <li class="long"><a href="?{{ templets.previous_page_number.querystring }}">上一页</a></li>
                  {% endif %}
                  <!-- 页码 -->
                  {% for page in templets.pages %}
                    {% if page %}
                      {% ifequal page templets.number %}
                        <li class="active"><a href="?page={{ page }}">{{ page }}<span
                                class="sr-only">(current)</span></a></li>
                      {% else %}
                        <li><a href="?{{ page.querystring }}">{{ page }}<span class="sr-only"></span></a></li>
                      {% endifequal %}
                    {% else %}
                      <li><a href="">...<span class="sr-only"></span></a></li>
                    {% endif %}
                  {% endfor %}
                  <!-- 下一页 -->
                  {% if templets.has_next %}
                    <li><a href="?{{ templets.next_page_number.querystring }}">下一页<span class="sr-only"></span></a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>



          </div>
        </div>
      </div>

    </div>


{% endblock content %}
{% block script %}
<!-- 添加框 -->
<div class="modal fade" id="AddTempletModal">
  <div class="modal-dialog" style="width: 1000px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">添加邮件模板</h4>
      </div>
      <div class="modal-body">
          <form method="post" id="js_addTempletForm">
              <label class="control-label" for="name">名称:</label>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="名称" id="name" name="name" />
            </div>
            <label class="control-label" for="subject">邮件标题:</label>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="标题" id="subject" name="subject" />
            </div>
            <label class="control-label" for="text">内容:</label>
            <div class="form-group">
                <textarea class="ckeditor" id="text" name="text"></textarea>
            </div>
              <!-- 设置编辑框高度 -->
            <script>
                CKEDITOR.replace('text', {
                    height: 550,
                });
            </script>
          </form>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary" id="js_addTemplet">保存</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->


<script>
//添加按钮提交
    $(function () {
        //处理ckeditor的值
        function CKupdate() {
            for (instance in CKEDITOR.instances)
                CKEDITOR.instances[instance].updateElement();
        }

        //提交表单
        $('#js_addTemplet').on('click', function () {
            CKupdate();
            toastr.options = {
                closeButton: false,
                debug: false,
                progressBar: false,
                positionClass: "toast-top-right",
                onclick: null,
                showDuration: "300",
                hideDuration: "1000",
                timeOut: "5000",
                extendedTimeOut: "1000",
                showEasing: "swing",
                hideEasing: "linear",
                showMethod: "fadeIn",
                hideMethod: "fadeOut"
            };
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'templets:add_templet' %}",
                dataType: 'json',
                data: $('#js_addTempletForm').serialize(),
                async: true,
                beforeSend: function (xhr, settings) {
                    // 这里需要csrf_token的值，而不是代码
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    if (data.status == 'success') {
                        toastr.options.timeOut = 1000;
                        toastr.options.onHidden = function() { window.location.href = "{% url 'templets:templet_list' %}"; }
                        toastr.success(data.msg);
                    } else if (data.status == 'fail') {
                        toastr.options.timeOut = 1000;
                        toastr.error(data.msg);
                    }
                }
            });
        })
    })
</script>

<!-- 删除框 -->
    {% for templet in templets.object_list %}
   <div class="modal fade modal-warning" id="DeleteTempletModal{{ templet.id }}">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">删除模板</h4>
          </div>
          <div class="modal-body">
             <div class="row" id="modal.flashes"></div>
              <form method="post" id="js_deleteTempletForm{{ templet.id }}">
                  <div class="form-group">
                      <p>是否删除该模板？</p>
                  </div>
              </form>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">关闭</button>
            <button type="button" class="btn btn-outline" id="js_deleteTemplet{{ templet.id }}">确认</button>
          </div>
        </div>

      </div>
    </div>

<script>
//删除
    $(function () {
        $('#js_deleteTemplet{{ templet.id }}').on('click', function () {
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'templets:del_templet' templet.id %}",
                data: $('#js_deleteTempletForm{{ templet.id }}').serialize(),
                async: true,
                beforeSend: function (xhr, settings) {
                    // 这里需要csrf_token的值，而不是代码
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    if (data.status == 'success') {
                        toastr.options.timeOut = 1000;
                        toastr.options.onHidden = function() { window.location.href = "{% url 'templets:templet_list' %}"; }
                        toastr.success(data.msg);
                    } else if (data.status == 'fail') {
                        toastr.error(data.msg);
                    }
                }
            });
        });
    });
    

</script>

{% endfor %}

<link href="{% static 'toastr/toastr.css' %}" rel="stylesheet"/>
<script src="{% static 'toastr/toastr.min.js' %}"></script>
{% endblock script %}