Phishing/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    # 用户url入口
    path('', include('users.urls', namespace='users')),
    # 验证码
    path('captcha/', include('captcha.urls')),
    # 联系人
    path('contacts/', include('contacts.urls', namespace='contacts')),
    # 邮件模板
    path('templets/', include('templets.urls', namespace='templets')),
    # 钓鱼页面
    path('pages/', include('pages.urls', namespace='pages')),
    # 发信配置
    path('smtp/', include('smtp.urls', namespace='smtp')),
    # 任务管理
    path('campaign/', include('campaigns.urls', namespace='campaign')),
    # 控制面板
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

apps/users/urls.py
########################################################################################################################
## Django 自带模块导入
########################################################################################################################
from django.conf.urls import url
from Phishing import settings

########################################################################################################################
## 系统自带模块导入
########################################################################################################################
from .views import *

########################################################################################################################
## 自建模块导入
########################################################################################################################


########################################################################################################################
## url
########################################################################################################################
app_name = 'users'

urlpatterns = [
    # 首页
    url(r'^$', IndexView.as_view(), name='index'),

    # 用户登录
    url(r'^login/$', LoginView.as_view(), name='login'),

    # 用户注销登录
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    # 忘记密码
    url(r'^forget/$', ForgetPasswordView.as_view(), name='forget_password'),

    # 重置密码页面
    url(r'^reset/(?P<reset_code>.*)$', ResetPasswordView.as_view(), name='reset_password'),

    # 重置密码
    url(r'^modify/$', ModifyPasswordView.as_view(), name='modify_password'),

    # 用户信息
    url(r'^user/info/$', UserInfoView.as_view(), name='user_info'),

    # 修改头像
    url(r'^user/change/avatar/$', ChangeAvatarView.as_view(), name='change_avatar'),

    # 修改密码
    url(r'^user/change/password/$', ChangePasswordView.as_view(), name='change_password'),

    # 发送修改邮箱验证码
    url(r'^user/send/change_email_code/$', SendChangeEmailCodeView.as_view(), name='send_change_email_code'),

    # 修改邮箱
    url(r'^user/change/email/$', ChangeEmailView.as_view(), name='change_email'),

    # 其他用户信息
    url(r'^other/user/info/(?P<uid>\d+)$', OtherUserInfoView.as_view(), name='other_user_info'),

    # 登录记录
    url(r'^user/login/record/$', UserLoginRecordView.as_view(), name='login_record'),

    # 用户列表
    url(r'^user/list/$', UserListView.as_view(), name='user_list'),

    # 用户状态管理
    url(r'^user/mana/status/(?P<uid>\d+)$', UserStatusManaView.as_view(), name='user_status_mana'),
]



apps/users/models.py
########################################################################################################################
## Django 自带模块导入
########################################################################################################################
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import Q


########################################################################################################################
## 系统自带模块导入
########################################################################################################################


########################################################################################################################
## 自建模块导入
########################################################################################################################



########################################################################################################################
## 用户模块
########################################################################################################################
class UserProfile(AbstractUser):
    name = models.CharField(verbose_name='姓名', max_length=20)
    role = models.CharField(verbose_name='用户角色', max_length=20)
    avatar = models.ImageField(verbose_name='用户头像', max_length=200, upload_to='users/avatar/%Y/%m',
                               default='users/avatar/default.png', null=True, blank=True)

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username




########################################################################################################################
## 邮箱验证码
########################################################################################################################
class EmailVerificationCode(models.Model):
    code = models.CharField(verbose_name='验证码', max_length=20)
    email = models.EmailField(verbose_name='接收邮箱')
    use = models.CharField(verbose_name='用途',
                           choices=(('register', '注册'), ('forget', '忘记密码'), ('change_email', '修改邮箱')), max_length=20)
    is_use = models.BooleanField(verbose_name='是否使用', default=False)
    add_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.code


########################################################################################################################
## 用户登录信息表
########################################################################################################################
class UserLoginRecord(models.Model):
    user = models.ForeignKey(UserProfile, verbose_name='用户', on_delete=models.CASCADE)
    agent = models.CharField(verbose_name='客户端', max_length=200, blank=True, null=True)
    ip = models.GenericIPAddressField(verbose_name='客户端IP', blank=True, null=True)
    add_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)

    class Meta:
        verbose_name = '用户登录信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user.username





















apps/users/views.py
########################################################################################################################
## Django 自带模块导入
########################################################################################################################
from django.shortcuts import render, HttpResponseRedirect
from django.views import View
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.hashers import make_password
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q

########################################################################################################################
## 系统自带模块导入
########################################################################################################################
import json
from pure_pagination import PageNotAnInteger, Paginator, EmptyPage
import datetime

########################################################################################################################
## 自建模块导入
########################################################################################################################
from .forms import *
from .models import *
from utils.mixin_utils import *
from utils.sendmail_utils import *
from utils.other_func import *


########################################################################################################################
## 首页类视图
########################################################################################################################
class IndexView(LoginRequiredMixin, View):

    def get(self, request):
        web_func = 'index'
        context = {
            'web_func':web_func,
        }


        return render(request, 'users/index.html', context=context)

########################################################################################################################
## 用户邮箱登陆
########################################################################################################################
class OtherLoginBackends(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            # 增加 Email, 同理增加手机都行
            user = UserProfile.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


########################################################################################################################
## 用户登录类视图
########################################################################################################################
class LoginView(View):
    def get(self, request):
        login_form = LoginForm()
        context = {
            'login_form': login_form,
        }
        return render(request, 'users/login.html', context=context)

    def post(self, request):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_name = request.POST.get('username')
            pass_word = request.POST.get('password')
            # 系统模块认认证用户
            user = authenticate(username=user_name, password=pass_word)
            # 判断用户认证结果
            if user is not None:
                if user.is_active:
                    login(request, user)
                    login_record = UserLoginRecord()
                    login_record.user = user
                    login_record.agent = request.META['HTTP_USER_AGENT']
                    login_record.ip = request.META['REMOTE_ADDR']
                 #   login_record.city = get_ip_location(request.META['REMOTE_ADDR'])
                    login_record.save()
                    return HttpResponseRedirect(reverse('users:index'))
                else:
                    msg = '用户未激活！'
                    context = {
                        'msg': msg,
                        'login_form': login_form,
                    }
                    return render(request, 'users/login.html', context=context)
            else:
                msg = '用户名或密码错误！'
                context = {
                    'msg': msg,
                    'login_form': login_form,
                }
                return render(request, 'users/login.html', context=context)
        else:
            context = {
                'login_form': login_form,
            }
            return render(request, 'users/login.html', context=context)


########################################################################################################################
## 用户注销登录视图
########################################################################################################################
class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('users:login'))


########################################################################################################################
## 用户找回密码
########################################################################################################################
class ForgetPasswordView(View):
    def get(self, request):
        return render(request, 'users/forget_password.html', context={})

    def post(self, request):
        # 实例化 email 表单
        forget_password_form = ForgetPasswordForm(request.POST)

        # 判断提交的数据合法性
        if forget_password_form.is_valid():
            email = request.POST.get('email')
            # 查找是否有该邮箱
            if UserProfile.objects.filter(email=email):
                send_status = send_email_verifycode(email, 'forget')
                if send_status:
                    return HttpResponse('{"status":"success", "msg":"发送成功！"}', content_type='application/json')
                else:
                    return HttpResponse('{"status":"fail", "msg":"邮件发送失败！"}', content_type='application/json')
            else:
                return HttpResponse('{"status":"fail", "msg":"发送失败，该用户不存在！"}', content_type='application/json')
        else:
            return HttpResponse('{"status":"fail", "msg":"发送失败，邮箱格式不合法！"}', content_type='application/json')


########################################################################################################################
## 用户重置密码页面
########################################################################################################################
class ResetPasswordView(View):
    def get(self, request, reset_code):
        code = reset_code
        email_records = EmailVerificationCode.objects.filter(code=code, use='forget')
        if email_records:
            email = email_records[0].email
            # 取出该用户最新的忘记密码验证码
            email_record = EmailVerificationCode.objects.filter(email=email, use='forget').order_by('-add_time')[0]

            if email_record.code == code and email_record.is_use == False:
                context = {
                    'email': email,
                }
                return render(request, 'users/reset_password.html', context=context)
            else:
                return HttpResponse('<h2>重置验证码已过期！</h2>')
        else:
            return HttpResponse('<h2>该验证码不存在！</h2>')


########################################################################################################################
## 用户重置密码过程
########################################################################################################################
class ModifyPasswordView(View):
    def post(self, request):
        reset_password_form = ResetPasswordForm(request.POST)
        email = request.POST.get('email')
        if reset_password_form.is_valid():
            pwd1 = request.POST.get('password1')
            pwd2 = request.POST.get('password2')
            if pwd1 == pwd2:
                user = UserProfile.objects.get(email=email)
                user.password = make_password(pwd1)
                user.save()
                email_record = EmailVerificationCode.objects.filter(use='forget', email=email).order_by('-add_time')[0]
                email_record.is_use = True
                email_record.save()
                return HttpResponse('{"status":"success", "msg":"密码重置成功！"}', content_type='application/json')
            else:
                return HttpResponse('{"status":"fail", "msg":"密码不一致或不符合长度要求！"}', content_type='application/json')
        else:
            return HttpResponse('{"status":"fail", "msg":"密码不一致或不符合长度要求！"}', content_type='application/json')


########################################################################################################################
## 用户个人信息中心
########################################################################################################################
class UserInfoView(LoginRequiredMixin, View):
    def get(self, request):
        web_title = 'user_manage'
        web_func = 'user_info'
        change_info_status = ''
        context = {
            'web_title': web_title,
            'web_func': web_func,
            'change_info_status': json.dumps(change_info_status),
        }
        return render(request, 'users/user_info.html', context=context)

    def post(self, request):
        web_title = 'user_manage'
        web_func = 'userinfo'
        change_userinfo_form = ChangeUserInfoForm(request.POST)
        if change_userinfo_form.is_valid():
            user = request.user
            user.save()

            change_info_status = 'success'
            context = {
                'web_title': web_title,
                'web_func': web_func,
                'change_info_status': json.dumps(change_info_status),
            }

templates/users/forget_password.html
{% extends 'users_base.html' %}
{% load staticfiles %}


<!-- 页面标题 -->
{% block web_title %}
  忘记密码 | Phishing
{% endblock web_title %}


<!-- 页面主体 -->
{% block web_content %}
  <div class="passwordBox animated fadeInDown">
    <div class="row" style="margin-top: 40%">

      <div class="col-md-12">
        <div class="ibox-content">

          <i class="glyphicon glyphicon-send" style="font-size: x-large; color: #1c2b36;">&nbsp;</i>
          <h2 class="font-bold" style="display: inline; color: #1c2b36;">忘记密码</h2>

          <p style="margin-top: 30px;">
            输入您的邮箱, 将会发一封重置找回密码邮件到您的邮箱中！
          </p>

          <!-- 邮箱表单 -->
          <div class="row">
            <div class="col-lg-12">
              <form class="m-t" role="form" action="" id="id_ForgetPasswordForm" method="post">
                <div class="form-group">
                  <input type="email" name="email" class="form-control" placeholder="邮箱地址" required="">
                </div>
                <input type="button" id="id_jsForgetPasswordBtn" class="btn btn-black block full-width m-b"
                       style="color: white" value="提交">
              </form>
            </div>
          </div>

          <small>记起密码? | <a href="{% url 'users:login' %}" style="color: #003366;">现在登录</a></small>

        </div>
      </div>
    </div>
  </div>
{% endblock web_content %}


{% block other_js %}
  <script>
      $(function () {
          // 提交表单
          $('#id_jsForgetPasswordBtn').on('click', function () {
              $.ajax({
                  cache: false,
                  type: "POST",
                  url: "{% url 'users:forget_password' %}",
                  data: $('#id_ForgetPasswordForm').serialize(),
                  async: true,
                  beforeSend: function (xhr, settings) {
                      // 这里需要csrf_token的值，而不是代码
                      xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                  },
                  success: function (data) {
                      if (data.status == 'success') {
                          $('#id_ForgetPasswordForm')[0].reset();
                          window.location.href = "{% url 'users:login' %}";
                          window.alert(data.msg);
                      } else if (data.status == 'fail') {
                          window.alert(data.msg);
                      }
                  }
              });
          });
      })
  </script>
{% endblock other_js %}


templates/users/login.html
{% extends 'users_base.html' %}
{% load staticfiles %}


<!-- 页面标题 -->
{% block web_title %}
  登录 | OPMS - 运维管理系统
{% endblock web_title %}

<!-- 其他css -->
{% block other_css %}
  <style>
    .captcha {
      float: right;
    }
  </style>
{% endblock other_css %}


<!-- 页面主体 -->
{% block web_content %}
  <div class="loginColumns animated fadeInDown">
    <div class="row" style="margin-top: 20%;">

      <!-- 登录框左边 -->
      <div class="col-md-6">
        <h2 class="-font-awesome">欢迎使用 Phishing 钓鱼邮件测试演练平台</h2>
        <div style="line-height: 30px; margin-top: 20px;">
          <small>由于该平台记录的都是关于安全管理组的一些数据，如非本部门内部成员，请您立即停止访问：</small>
          <p><b>Thank you so much for the cooperation！</b></p>
        </div>
      </div>

      <!-- 登录框右边 -->
      <div class="col-md-6">
        <div class="ibox-content">
          <div>
            <i class="glyphicon glyphicon-send" style="font-size: x-large; color: #1c2b36;;">&nbsp;</i>
            <span class="font-bold text-center" style="font-size: 30px; font-family: inherit; color: #1c2b36;">登录</span>
          </div>
          <form class="m-t" role="form" method="post" action="{% url 'users:login' %}">
            {% csrf_token %}

            <!-- 用户名或者邮箱 -->
            <div class="form-group">
              <input type="text" class="form-control" name="username" placeholder="用户名/邮箱" required="">
            </div>

            <!-- 密码 -->
            <div class="form-group">
              <input type="password" class="form-control" name="password" placeholder="密码" required="">
            </div>

            <div class="form-group">
              {{ login_form.captcha }}

              <!-- 错误提示 -->
              {% if msg %}
                <p style="color: red; margin-top: 10px;">{{ msg }}</p>
              {% else %}
                <p style="color: red; margin-top: 10px;">{{ login_form.errors.captcha|cut:'<ul class="errorlist"><li>' }}</p>
              {% endif %}

              <!-- 刷新验证码 -->
              <script>
                  function refresh_captcha() {
                      $.getJSON("/captcha/refresh/",
                          function (result) {
                              $('.captcha').attr('src', result['image_url']);
                              $('#id_captcha_0').val(result['key'])
                          })
                  }

                  $('.captcha').click(refresh_captcha)
              </script>
            </div>

            <!-- 登录按钮 -->
            <button type="submit" class="btn bg-black block full-width m-b" style="color: white">登录</button>

            <small>忘记密码? | <a href="{% url 'users:forget_password' %}" style="color: #003366;">现在找回</a></small>

            <p class="text-muted text-center">
            </p>
          </form>
          <p class="m-t">
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock web_content %}


<!-- 其他js -->
{% block other_js %}
  <script>
    document.getElementById("id_captcha_1").style.width = '60%';
    document.getElementById("id_captcha_1").className = 'form-control';
    document.getElementById("id_captcha_1").setAttribute("placeholder","验证码");
  </script>
{% endblock other_js %}

templates/users/login_record.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- 标题 -->
{% block title %}
  登录记录
{% endblock title %}

<!-- 内容主体 -->
{% block content %}
  <div class="col">
    <p style="height: 2px;"></p>
    <!-- 中间栏 -->
    <div class="padder">
      <!-- 用户反馈 -->
      <div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <div style="border-left: 4px solid #003366; margin-bottom: 10px; margin-top: 10px; height: 25px;font-size: 18px;">
              <span>&nbsp;&nbsp;登录记录</span>
            </div>
          </div>
          <div class="panel-body" style="height: 745px;">

            <div id="editable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-12">
                  <form class="navbar-form pull-right " role="search" method="get" style="margin-top: 0;">
                    <div class="form-group">
                      <div class="input-group">
                        <input type="text" class="form-control input-sm bg-light no-border rounded" name="keywords" placeholder="关键词搜索" style="width: 150px;">
                        <span class="input-group-btn">
                        <button type="submit" class="btn btn-sm bg-auto rounded"><i class="fa fa-search"></i></button>
                      </span>
                      </div>
                    </div>
                  </form>
                </div>
              </div>

              <div class="row" style="height: 610px;">
                <div class="col-sm-12">

                  <table class="table table-striped table-bordered table-hover dataTable no-footer" id="editable"
                         role="grid">

                    <!-- 标题行 -->
                    <thead>
                    <tr role="row">
                      <th class="text-center" rowspan="1" colspan="1" style="width: 46px;">ID</th>
                      <th class="text-center" rowspan="1" colspan="1" style="width: 87px;">用户名</th>
                      <th class="text-center" rowspan="1" colspan="1" style="width: 114px;">姓名</th>
                      <th class="text-center" rowspan="1" colspan="1" style="width: 171px;">客户端</th>
                      <th class="text-center" rowspan="1" colspan="1" style="width: 148px;">IP地址</th>
{#                      <th class="text-center" rowspan="1" colspan="1" style="width: 80px;">城市</th>#}
                      <th class="text-center" rowspan="1" colspan="1" style="width: 184px;">日期</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for each_record in all_records.object_list %}
                      <tr class="gradeX {% if forloop.counter|divisibleby:'2' %}odd{% else %}even{% endif %}"
                          role="row">
                        <td class="text-center" style="vertical-align : middle;">{{ forloop.counter }}</td>
                        <td class="text-center" style="vertical-align : middle;">{{ each_record.user.username }}</td>
                        <td class="text-center" style="vertical-align : middle;">{{ each_record.user.nick_name }}</td>
                        <td class="text-center" style="vertical-align : middle;">{{ each_record.agent|slice:'35' }}...</td>
                        <td class="text-center" style="vertical-align : middle;">{{ each_record.ip }}</td>
{#                        <td class="text-center" style="vertical-align : middle;">{{ each_record.city }}</td>#}
                        <td class="text-center" style="vertical-align : middle;">{{ each_record.add_time }}</td>
                      </tr>
                    {% endfor %}

                    </tbody>
                  </table>

                </div>
              </div>
            </div>

            <!-- 页码 -->
            <div class="row">
              <div class="col-md-12 text-center">
                <ul class="pagination">
                  <!-- 上一页 -->
                  {% if all_records.has_previous %}
                    <li class="long"><a href="?{{ all_records.previous_page_number.querystring }}">上一页</a></li>
                  {% endif %}
                  <!-- 页码 -->
                  {% for page in all_records.pages %}
                    {% if page %}
                      {% ifequal page all_records.number %}
                        <li class="active"><a href="?page={{ page }}">{{ page }}<span
                                class="sr-only">(current)</span></a></li>
                      {% else %}
                        <li><a href="?{{ page.querystring }}">{{ page }}<span class="sr-only"></span></a></li>
                      {% endifequal %}
                    {% else %}
                      <li><a href="">...<span class="sr-only"></span></a></li>
                    {% endif %}
                  {% endfor %}
                  <!-- 下一页 -->
                  {% if all_records.has_next %}
                    <li><a href="?{{ all_records.next_page_number.querystring }}">下一页<span class="sr-only"></span></a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/users/reset_password.html
{% extends 'users_base.html' %}
{% load staticfiles %}


<!-- 页面标题 -->
{% block web_title %}
  重置密码 | Phishing
{% endblock web_title %}


<!-- 页面主体 -->
{% block web_content %}
  <div class="passwordBox animated fadeInDown">
  <div class="row" style="margin-top: 30%">

    <div class="col-md-12">
      <div class="ibox-content">

        <i class="glyphicon glyphicon-send" style="font-size: x-large; color: #1c2b36;">&nbsp;</i>
        <h2 class="font-bold" style="display: inline; color: #1c2b36;">重置密码</h2>

        <p style="margin-top: 30px;">
          请您设置一个满足密码复杂度并能够被您记住的密码！
        </p>

        <!-- 重置密码表单 -->
        <div class="row">
          <div class="col-lg-12">
            <form class="m-t" role="form" action="" id="id_ForgetPasswordForm" method="post">
              <div class="form-group">
                <input type="password" class="form-control" name="password1" placeholder="新密码" required="">
              </div>

              <div class="form-group">
                <input type="password" class="form-control" name="password2" placeholder="重复密码" required="">
              </div>

              <p style="color: red">{{ msg }}</p>

              <input type="hidden" name="email" value="{{ email }}">

              <input type="button" id="id_jsResetPasswordBtn" class="btn btn-black block full-width m-b" style="color: white" value="提交">
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock web_content %}


{% block other_js %}
  <script>
      $(function () {
          // 提交表单
          $('#id_jsResetPasswordBtn').on('click', function () {
              $.ajax({
                  cache: false,
                  type: "POST",
                  url: "{% url 'users:modify_password' %}",
                  data: $('#id_ForgetPasswordForm').serialize(),
                  async: true,
                  beforeSend: function (xhr, settings) {
                      // 这里需要csrf_token的值，而不是代码
                      xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                  },
                  success: function (data) {
                      if (data.status == 'success') {
                          $('#id_ForgetPasswordForm')[0].reset();
                          window.location.href = "{% url 'users:login' %}";
                          window.alert(data.msg);
                      } else if (data.status == 'fail') {
                          window.alert(data.msg);
                      }
                  }
              });
          });
      })
  </script>
{% endblock other_js %}
