Phishing/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    # 用户url入口
    path('', include('users.urls', namespace='users')),
    # 验证码
    path('captcha/', include('captcha.urls')),
    # 联系人
    path('contacts/', include('contacts.urls', namespace='contacts')),
    # 邮件模板
    path('templets/', include('templets.urls', namespace='templets')),
    # 钓鱼页面
    path('pages/', include('pages.urls', namespace='pages')),
    # 发信配置
    path('smtp/', include('smtp.urls', namespace='smtp')),
    # 任务管理
    path('campaign/', include('campaigns.urls', namespace='campaign')),
    # 控制面板
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

apps/contacts/urls.py
########################################################################################################################
## Django 自带模块导入
########################################################################################################################
from django.urls import path


########################################################################################################################
## 系统自带模块导入
########################################################################################################################
from .views import *
########################################################################################################################
## 自建模块导入
########################################################################################################################


########################################################################################################################
## url
########################################################################################################################
app_name = 'contacts'

urlpatterns = [
    # 联系人
    path('linkman/list', LinkmanListView.as_view(), name='linkman_list'),
    # 添加联系人
    path('linkman/add', AddLinkman.as_view(), name='add_linkman'),
    # 编辑联系人
    path('linkman/edit/<int:l_id>', EditLinkman.as_view(), name='edit_linkman'),
    # 删除联系人
    path('linkman/del/<int:l_id>', DeleteLinkman.as_view(), name='del_linkman'),
    # 部门
    path('depart/list', DepartListView.as_view(), name='depart_list'),
    # 添加部门
    path('depart/add', AddDepart.as_view(), name='add_depart'),
    # 编辑部门
    path('depart/edit/<int:d_id>', EditDepart.as_view(), name='edit_depart'),
    # 删除部门
    path('depart/del/<int:d_id>', DeleteDepart.as_view(), name='del_depart'),
    # 分组
    path('group/list', GroupListView.as_view(), name='group_list'),
    # 添加分组
    path('group/add', AddGroup.as_view(), name='add_group'),
    # 删除分组
    path('group/del/<int:g_id>', DeleteGroup.as_view(), name='del_group'),
    # 分组详情
    path('group/detail/<int:g_id>', GroupDetail.as_view(), name='group_detail'),
    # 批量导入
    path('import/', BatchImport.as_view(), name='batch_import'),
]

apps/contacts/models.py
from django.db import models


# Create your models here.

################################################################################################################
## 部门
#################################################################################################################
class Department(models.Model):
    name = models.CharField(verbose_name="部门名称", max_length=40)

    class Meta:
        verbose_name = "部门"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


################################################################################################################
## 联系人
################################################################################################################


class Linkman(models.Model):
    name = models.CharField(verbose_name="姓名", max_length=20)
    email = models.EmailField(verbose_name="邮箱地址")
    depart = models.ForeignKey(Department, verbose_name="部门", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "联系人"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


##############################################################################################################
## 分组
##############################################################################################################
class Group(models.Model):
    name = models.CharField(verbose_name="分组名称", max_length=20)
    group_members = models.ManyToManyField(Linkman)

    class Meta:
        verbose_name = "分组"
        verbose_name_plural = verbose_name

    def get_members(self):
        return "\n".join([m.name for m in self.group_members.all()])

    def get_id_list(self):
        id_list = []
        for m in self.group_members.all():
            id_list.append(m.id)
        return id_list

    def get_email_list(self):
        email_list = []
        for m in self.group_members.all():
            email_list.append(m.email)
        return email_list

    def get_name_list(self):
        name_list = []
        for m in self.group_members.all():
            name_list.append(m.name)
        return name_list

    def get_id_email_dict(self):
        id_email_dict = []
        for m in self.group_members.all():
            id_email_dict.append((m.id, m.email))
        return id_email_dict

    def __str__(self):
        return self.name

apps/contacts/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/12/10 8:19 下午
# @Author  : twosmi1e
# @Site    : 
# @File    : forms.py
# @Software: PyCharm

from django import forms

from .models import *


class AddLinkmanForm(forms.Form):
    name = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(required=True)
    depart = forms.CharField(max_length=40, required=False)


class AddDepartForm(forms.Form):
    name = forms.CharField(max_length=20, required=True)


class AddGroupForm(forms.Form):
    name = forms.CharField(max_length=20, required=True)
    group_members = forms.ModelMultipleChoiceField(queryset=Linkman.objects.all())

apps/contacts/views.py
from django.shortcuts import render

# Create your views here.
########################################################################################################################
## Django 自带模块导入
########################################################################################################################
from django.shortcuts import render, HttpResponseRedirect
from django.views import View
from django.http import HttpResponse
from django.db.models import Q

########################################################################################################################
## 系统自带模块导入
########################################################################################################################
import json
import xlrd
from pure_pagination import PageNotAnInteger, Paginator, EmptyPage

########################################################################################################################
## 自建模块导入
########################################################################################################################
from .forms import *
from .models import *
from utils.mixin_utils import *
from .task import *

########################################################################################################################
## 联系人列表视图
########################################################################################################################
class LinkmanListView(LoginRequiredMixin, View):
    def get(self, request):
        web_title = 'linkman_manage'
        web_func = 'linkman_list'
        all_linkman = Linkman.objects.all()
        departments = Department.objects.all()
        keywords = request.GET.get('keywords', '')

        if keywords != '':
            all_linkman = all_linkman.filter(
                Q(id__icontains=keywords) |
                Q(name__icontains=keywords) |
                Q(email__icontains=keywords) |
                Q(depart__name__icontains=keywords)
            )

        # 判断页码
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        # 对取到的数据进行分页，记得定义每页的数量
        p = Paginator(all_linkman, 12, request=request)

        # 分页处理后的 QuerySet
        all_linkman = p.page(page)

        context = {
            'web_title': web_title,
            'web_func': web_func,
            'all_linkman': all_linkman,
            'departments': departments,
        }
        return render(request, 'contacts/linkman_list.html', context=context)

########################################################################################################################
## 添加联系人
########################################################################################################################
class AddLinkman(LoginRequiredMixin, View):
    def post(self, request):
        add_linkman_host = AddLinkmanForm(request.POST)
        if add_linkman_host.is_valid():
            if Linkman.objects.filter(email=request.POST.get('email')):
                return HttpResponse('{"status":"fail", "msg":"记录已存在！"}', content_type='application/json')
            linkman = Linkman()
            linkman.name = request.POST.get('name')
            linkman.email = request.POST.get('email')
            linkman.depart_id = request.POST.get('depart')
            linkman.save()
            return HttpResponse('{"status":"success", "msg":"记录添加成功！"}', content_type='application/json')

        return HttpResponse('{"status":"fail", "msg":"内容不符合要求！"}', content_type='application/json')


########################################################################################################################
## 编辑联系人
########################################################################################################################
class EditLinkman(LoginRequiredMixin, View):
    def post(self, request, l_id):
        linkman = Linkman.objects.get(id=int(l_id))
        edit_linkman_form = AddLinkmanForm(request.POST)
        if edit_linkman_form.is_valid():
            linkman.name = request.POST.get('name')
            linkman.email = request.POST.get('email')
            linkman.depart_id = request.POST.get('depart')
            linkman.save()
            return HttpResponse('{"status":"success", "msg":"编辑成功!"}', content_type='application/json')

        return HttpResponse('{"status":"fail", "msg":"修改失败!"}', content_type='application/json')


########################################################################################################################
## 删除联系人
########################################################################################################################
class DeleteLinkman(LoginRequiredMixin, View):
    def post(self, request, l_id):
        try:
            linkman = Linkman.objects.get(id=int(l_id))
            linkman.delete()
            return HttpResponse('{"status":"success", "msg":"删除成功"}', content_type='application/json')
        except Exception as e:
            return HttpResponse('{"status":"fail", "msg":"删除失败"}', content_type='application/json')

########################################################################################################################
## 部门列表视图
########################################################################################################################
class DepartListView(LoginRequiredMixin, View):
    def get(self, request):
        web_title = 'depart_manage'
        web_func = 'depart_list'
        departments = Department.objects.all()
        # 用户搜索
        keywords = request.GET.get('keywords', '')

        if keywords != '':
            departments = departments.filter(
                Q(id__icontains=keywords) |
                Q(name__icontains=keywords)
            )


        # 判断页码
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        # 对取到的数据进行分页，记得定义每页的数量
        p = Paginator(departments, 12, request=request)

        # 分页处理后的 QuerySet
        departments = p.page(page)

        context = {
            'web_title': web_title,
            'web_func': web_func,
            'departments': departments,
        }
        return render(request, 'contacts/depart_list.html', context=context)


########################################################################################################################
## 添加部门
########################################################################################################################
class AddDepart(LoginRequiredMixin, View):
    def post(self, request):
        add_depart = AddDepartForm(request.POST)
        if add_depart.is_valid():
            if Department.objects.filter(name=request.POST.get('name')):
                return HttpResponse('{"status":"fail", "msg":"部门已存在！"}', content_type='application/json')
            depart = Department()
            depart.name = request.POST.get('name')

            depart.save()
            return HttpResponse('{"status":"success", "msg":"添加成功！"}', content_type='application/json')

        return HttpResponse('{"status":"fail", "msg":"内容不符合要求！"}', content_type='application/json')


########################################################################################################################
## 编辑部门
########################################################################################################################
class EditDepart(LoginRequiredMixin, View):
    def post(self, request, d_id):
        depart = Department.objects.get(id=int(d_id))
        edit_depart_form = AddDepartForm(request.POST)
        if edit_depart_form.is_valid():
            depart.name = request.POST.get('name')
            depart.save()
            return HttpResponse('{"status":"success", "msg":"编辑成功!"}', content_type='application/json')

        return HttpResponse('{"status":"fail", "msg":"修改失败!"}', content_type='application/json')

########################################################################################################################
## 删除部门
########################################################################################################################
class DeleteDepart(LoginRequiredMixin, View):
    def post(self, request, d_id):
        try:
            depart = Department.objects.get(id=int(d_id))
            depart.delete()
            return HttpResponse('{"status":"success", "msg":"删除成功"}', content_type='application/json')
        except Exception as e:
            return HttpResponse('{"status":"fail", "msg":"删除失败"}', content_type='application/json')

########################################################################################################################
## 分组列表
########################################################################################################################
class GroupListView(LoginRequiredMixin, View):
    def get(self, request):
        web_title = 'group_manage'
        web_func = 'group_list'
        groups = Group.objects.all()
        linkmen = Linkman.objects.all()
        keywords = request.GET.get('keywords', '')

        if keywords != '':
            groups = groups.filter(
                Q(id__icontains=keywords) |
                Q(name__icontains=keywords) |
                Q(group_members__name__icontains=keywords)
            )

        # 判断页码
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        # 对取到的数据进行分页，记得定义每页的数量
        p = Paginator(groups, 9, request=request)

        # 分页处理后的 QuerySet
        groups = p.page(page)

        context = {
            'web_title': web_title,
            'web_func': web_func,
            'groups': groups,
            'linkmen': linkmen,
        }
        return render(request, 'contacts/group_list.html', context=context)

########################################################################################################################

templates/contacts/depart_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
  部门列表
{% endblock title %}

<!-- 主体 -->
{% block content %}
  <div class="col">
    <p style="height: 2px;"></p>
    <!-- 中间栏 -->
    <div class="padder">
      <!-- 部门列表 -->
      <div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <div style="border-left: 4px solid #003366; margin-bottom: 10px; margin-top: 10px; height: 25px;font-size: 18px;">
              <span>&nbsp;&nbsp;部门列表</span>
            </div>
          </div>
          <div class="panel-body container" style="height: 745px;">
            <div class="module-option clearfix">
              <form class="navbar-form pull-left " role="search" method="get" style="margin-top: 0px;">
                <div class="form-group">
                  <div class="input-group">
                    <input type="text" class="form-control input-sm bg-light no-border rounded" name="keywords"
                           placeholder="关键词搜索" style="width: 150px;">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-sm bg-auto rounded"><i class="fa fa-search"></i></button>
                      </span>
                  </div>
                </div>
              </form>
                <div class="navbar-btn pull-right" style="margin-top: 0px;width: 150px;">
                    <span>
                          <button type="button" class="btn btn-block btn-success" data-toggle="modal" data-target="#AddDepartModal"><i class="fa fa-plus"></i> 添加部门</button>
                      </span>
                </div>
            </div>


         <div class="row" style="height: 610px;">
                <div class="col-sm-12">

                  <table class="table table-hover table-bordered dataTable" id="departtable" role="grid">

                    <!-- 标题行 -->
                    <thead>
                    <tr role="row">
                      <th class="text-center" rowspan="1" colspan="1" style="">ID</th>
                      <th class="text-center sorting" rowspan="1" colspan="1" style="">部门</th>
                      <th class="text-center" rowspan="1" colspan="1">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for each_depart in departments.object_list %}
                      <tr class="gradeX {% if forloop.counter|divisibleby:'2' %}odd{% else %}even{% endif %}"
                          role="row">
                        <td class="text-center" style="vertical-align : middle;">{{ forloop.counter }}</td>
                        <td class="text-center" style="vertical-align : middle;">{{ each_depart.name }}</td>
                        <td class="text-center" style="vertical-align: middle;">
                            <button class="btn btn-info" data-toggle="modal" data-target="#EditDepartModal{{ each_depart.id }}">编辑</button>
                            <button class="btn btn-danger" data-toggle="modal" data-target="#DeleteDepartModal{{ each_depart.id }}">删除</button>
                        </td>
                      </tr>
                    {% endfor %}

                    </tbody>
                  </table>



                </div>
              </div>
            </div>

            <!-- 页码 -->
            <div class="row">
              <div class="col-md-12 text-center">
                <ul class="pagination">
                  <!-- 上一页 -->
                  {% if departments.has_previous %}
                    <li class="long"><a href="?{{ departments.previous_page_number.querystring }}">上一页</a></li>
                  {% endif %}
                  <!-- 页码 -->
                  {% for page in departments.pages %}
                    {% if page %}
                      {% ifequal page departments.number %}
                        <li class="active"><a href="?page={{ page }}">{{ page }}<span
                                class="sr-only">(current)</span></a></li>
                      {% else %}
                        <li><a href="?{{ page.querystring }}">{{ page }}<span class="sr-only"></span></a></li>
                      {% endifequal %}
                    {% else %}
                      <li><a href="">...<span class="sr-only"></span></a></li>
                    {% endif %}
                  {% endfor %}
                  <!-- 下一页 -->
                  {% if departments.has_next %}
                    <li><a href="?{{ departments.next_page_number.querystring }}">下一页<span class="sr-only"></span></a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>


          </div>
        </div>
      </div>

    </div>


{% endblock content %}
{% block script %}
    <!-- 添加框 -->

        <div class="modal fade" id="AddDepartModal">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">新部门</h4>
              </div>
              <div class="modal-body">
                 <div class="row" id="modal.flashes"></div>
                  <form method="post" id="js_addDepartForm">
                      <label class="control-label" for="name">部门名:</label>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="部门名" id="name" autofocus />
                    </div>
                  </form>

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="js_addDepart">保存</button>
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
<script>

      $(function () {
          // 提交表单
          $('#js_addDepart').on('click', function () {
              var name = $('#name').val();
             // if (check_email() == false || check_name() == false):
              toastr.options = {
                closeButton: false,
                debug: false,
                progressBar: false,
                positionClass: "toast-top-right",
                onclick: null,
                showDuration: "300",
                hideDuration: "1000",
                timeOut: "5000",
                extendedTimeOut: "1000",
                showEasing: "swing",
                hideEasing: "linear",
                showMethod: "fadeIn",
                hideMethod: "fadeOut"
              };
              $.ajax({
                  cache: false,
                  type: "POST",
                  url: "{% url 'contacts:add_depart' %}",
                  dataType: 'json',
                  data: {
                      'name':name,
                  },
                  async: true,
                  beforeSend: function (xhr, settings) {
                      // 这里需要csrf_token的值，而不是代码
                      xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                  },
                  success: function (data) {
                      if (data.status == 'success') {
                          toastr.options.timeOut = 1000;
                          toastr.options.onHidden = function() { window.location.href = "{% url 'contacts:depart_list' %}"; }
                          toastr.success(data.msg);
                      } else if (data.status == 'fail') {
                          toastr.error(data.msg);
                      }
                  }
              });
          });
      });
</script>
     <!-- 编辑框 -->
    {% for depart in departments.object_list %}
        <div class="modal fade" id="EditDepartModal{{ depart.id }}">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">编辑</h4>
              </div>
            <form id="js_editDepartForm{{ depart.id }}">
              <div class="modal-body">
                 <div class="row" id="modal.flashes"></div>
                  <label class="control-label" for="name">部门名:</label>
                  <div class="form-group">
                      <input type="text" class="form-control" placeholder="部门名" value="{{ depart.name }}" name="name" />
                  </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="js_editDepart{{ depart.id }}">保存</button>
              </div>
            </form>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
<script>
    //编辑
    $(function () {
        //提交表单
        $('#js_editDepart{{ depart.id }}').on('click', function () {
            toastr.options = {
                closeButton: false,
                debug: false,
                progressBar: false,
                positionClass: "toast-top-right",
                onclick: null,
                showDuration: "300",
                hideDuration: "1000",
                timeOut: "1000",
                extendedTimeOut: "1000",
                showEasing: "swing",
                hideEasing: "linear",
                showMethod: "fadeIn",
                hideMethod: "fadeOut"
            };
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'contacts:edit_depart' depart.id %}",
                data: $('#js_editDepartForm{{ depart.id }}').serialize(),
                async: true,
                beforeSend: function (xhr, settings) {
                  // 这里需要csrf_token的值，而不是代码
                  xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                  if (data.status == 'success') {
                      toastr.options.timeOut = 1000;
                      toastr.options.onHidden = function() { window.location.href = "{% url 'contacts:depart_list' %}"; }
                      toastr.success(data.msg);
                  } else if (data.status == 'fail') {
                      toastr.error(data.msg);
                  }
                }
            });
        })
    })
</script>

    <!-- 删除 -->
    <div class="modal fade modal-warning" id="DeleteDepartModal{{ depart.id }}">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">删除部门</h4>
          </div>
          <div class="modal-body">
             <div class="row" id="modal.flashes"></div>
              <form method="post" id="js_deleteDepartForm{{ depart.id }}">
                  <div class="form-group">
                      <p>是否删除该部门？</p>
                  </div>
              </form>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">关闭</button>
            <button type="button" class="btn btn-outline" id="js_deleteDepart{{ depart.id }}">确认</button>
          </div>
        </div>
      </div>
    </div>

<script>
    //删除
    $(function () {
        $('#js_deleteDepart{{ depart.id }}').on('click', function () {
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'contacts:del_depart' depart.id %}",
                data: $('#js_deleteDepartForm{{ depart.id }}').serialize(),
                async: true,
                beforeSend: function (xhr, settings) {
                    // 这里需要csrf_token的值，而不是代码
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    if (data.status == 'success') {
                        toastr.options.timeOut = 1000;
                        toastr.options.onHidden = function() { window.location.href = "{% url 'contacts:depart_list' %}"; }
                        toastr.success(data.msg);
                    } else if (data.status == 'fail') {
                        toastr.error(data.msg);
                    }
                }
            });
        });
    })
</script>
    {% endfor %}

<link href="{% static 'toastr/toastr.css' %}" rel="stylesheet"/>
<script src="{% static 'toastr/toastr.min.js' %}"></script>
{% endblock script %}